services:
  meshinfo:
    image: ghcr.io/dadecoza/meshinfo:latest
    volumes:
      - ./config.json:/app/config.json
      - ./output:/app/output
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - 9000:9000
      - 8000:8000
    restart: always
 