services:
  meshinfo:
    image: ghcr.io/dadecoza/meshinfo-lite:0.1.5-za
    volumes:
      - ./config.ini:/app/config.ini
      - ./process_payload.py:/app/process_payload.py
      - ./templates:/app/templates
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - 8000:8000
    networks:
      - backend
    restart: always
  
networks:       
  backend:
    driver: bridge
